catalog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('admin_home', views.home_admin, name='home_admin'),
    path('home/<int:pk>', views.home_client, name='home_client'),
    path('login/', views.login_cust, name='login'),

    path('my_purchases/<int:pk>', views.my_purchases, name='my_purchases'),
    path('goods/<int:pk>', views.goods, name='goods'),
    path('purchase/<int:customer_pk>/<int:item_pk>/', views.purchase, name='purchase'),

    path('edit_request', views.edit_request, name='edit_request'),

    path('statistics',  views.statistics, name='statistics'),
    path('choose_a_company', views.choosing, name='choose_a_company'),
    path('agreement_pdf/<int:supplier_id>', views.generate_pdf, name='generate_document'),
    path('choose_a_receipt', views.choosing_r, name='choose_a_receipt'),
    path('receipt_pdf/<int:receipt_id>', views.generate_r, name='generate_receipt'),

    path('items', views.list_item, name='lists_item'),
    path('fabrics', views.list_fabric, name='lists_fabric'),
    path('suppliers', views.list_supplier, name='lists_supplier'),
    path('customers', views.list_customer, name='lists_customer'),
    path('receipts', views.list_receipt, name='lists_receipt'),

    path('items/new', views.CreateItemView.as_view(), name='new_lists'),
    path('edit_item/<int:pk>/', views.UpdateItemView.as_view(), name='edit_item'),
    path('delete_item/<int:pk>/', views.DeleteItemView.as_view(), name='delete_item'),

    path('customer/new', views.CreateCustomerView.as_view(), name='new_customer'),
    path('customer/new_account', views.CreateCustomer2View.as_view(), name='new_customer_account'),
    path('edit_customer/<int:pk>/', views.UpdateCustomerView.as_view(), name='edit_customer'),
    path('edit_my_profile/<int:pk>/', views.UpdateCustomer2View.as_view(), name='edit_my_profile'),
    path('delete_customer/<int:pk>/', views.DeleteCustomerView.as_view(), name='delete_customer'),

    path('fabric/new', views.CreateFabricView.as_view(), name='new_fabric'),
    path('edit_fabric/<int:pk>/', views.UpdateFabricView.as_view(), name='edit_fabric'),
    path('delete_fabric/<int:pk>/', views.DeleteFabricView.as_view(), name='delete_fabric'),

    path('supplier/new', views.CreateSupplierView.as_view(), name='new_supplier'),
    path('edit_supplier/<int:pk>/', views.UpdateSupplierView.as_view(), name='edit_supplier'),
    path('delete_supplier/<int:pk>/', views.DeleteSupplierView.as_view(), name='delete_supplier'),

    path('receipt/new', views.CreateReceiptView.as_view(), name='new_receipt'),
    path('edit_receipt/<int:pk>/', views.UpdateReceiptView.as_view(), name='edit_receipt'),
    path('delete_receipt/<int:pk>/', views.DeleteReceiptView.as_view(), name='delete_receipt'),

]

locallib/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.db import models
from django.core.validators import RegexValidator
import random
from datetime import datetime


name_regex = r'^[А-ЩЬЮЯҐЄІЇа-щьюяґєії\'\s]+$'
name_validator = RegexValidator(
    regex=name_regex,
    message="Використовуйте українську мову.",
    code='invalid_name'
)

phone_regex = r"^\+380 \d{2}-\d{3}-\d{2}-\d{2}$"
phone_validator = RegexValidator(
    regex=phone_regex,
    message="Номер телефона повинен бути у форматі: '+380 12-345-67-89'.",
    code='invalid_phone_number'
)

password_regex = r"^(?=.*[A-Za-z])(?=.*\d)(?=.*[$!%*#?&+])[A-Za-z\d@$!%*#?&+]{8,}$"
password_validator = RegexValidator(
    regex=password_regex,
    message="Від 8 символів, латинська літера, цифра та спеціальний символ",
    code='invalid_password'
)

card_regex = r"^\d{4} \d{4} \d{4} \d{4}$"
card_validator = RegexValidator(
    regex=card_regex,
    message="Номер картки записується у вигляді хххх хххх хххх хххх",
    code='invalid_card'
)
passport_regex = r'^[1-9]\d{9}$'
passport_validator = RegexValidator(
    regex=passport_regex,
    message="Номер паспорта не починається з 0 та містить 10 символів",
    code='invalid_passport'
)
date_regex = r'^(500|[1-4]?[0-9]{1,2})$'
date_validator = RegexValidator(
    regex=date_regex,
    message="Введіть число від 1 до 500.",
    code='invalid_number'
)

class Fabric(models.Model):
    DESTINY = (
        ('Висока', 'Висока'),
        ('Помірна', 'Помірна'),
        ('Середня', 'Середня'),
        ('Низька', 'Низька'),
        ('Різна', 'Різна'),
    )
    ELASTICITY = (
        ('Не еластична', 'Не еластична'),
        ('Майже не еластична', 'Майже не еластична'),
        ('Частково еластична', 'Частково еластична'),
        ('Добре еластична', 'Добре еластична')
    )

    BREATHABILITY = (
        ('Низька', 'Низька'),
        ('Майже відсутня', 'Майже відсутня'),
        ('Середня', 'Середня'),
        ('Висока', 'Висока')
    )

    TEXTURE = (
        ('Блискуча', 'Блискуча'),
        ('Гладка', 'Гладка'),
        ('Гофрована', 'Гофрована'),
        ('Діагональна', 'Діагональна'),
        ('Матова', 'Матова'),
        ('М\'яка', 'М\'яка'),
        ('Рельєфна', 'Рельєфна'),
        ('Рубчаста', 'Рубчаста'),
        ('Сітчаста', 'Сітчаста'),
        ('Складна', 'Складна'),
        ('Смужкова', 'Смужкова'),
        ('Шорстка', 'Шорстка')
    )

    RESISTANCE = (
        ('Висока стійкість', 'Висока стійкість'),
        ('Середня стійкість', 'Середня стійкість'),
        ('Низька стійкість', 'Низька стійкість'),
        ('Антикомпресійна тканина', 'Антикомпресійна тканина')
    )

    FASTNESS = (
        ('Висока стійкість', 'Висока стійкість'),
        ('Середня стійкість', 'Середня стійкість'),
        ('Низька стійкість', 'Низька стійкість'),
        ('Невідомо', 'Невідомо')
    )
    id_fabric = models.AutoField(primary_key=True)
    fabric_name = models.CharField('Назва тканини', validators=[name_validator], unique=True, max_length=30)
    destiny = models.CharField('Щільність', max_length=30, choices=DESTINY)
    elasticity = models.CharField('Еластичність', max_length=30, choices=ELASTICITY)
    breathability = models.CharField('Повітропроникність', max_length=30, choices=BREATHABILITY)
    surface_texture = models.CharField('Текстура', max_length=30, choices=TEXTURE)
    compression_resistance = models.CharField('Стійкість до стиснення', max_length=30, choices=RESISTANCE)
    color_fastness = models.CharField('Стійкість кольору', max_length=30, choices=FASTNESS)

    def __str__(self):
        return self.fabric_name

    class Meta:
        app_label = 'catalog'


class Supplier(models.Model):
    id_supplier = models.AutoField(primary_key=True)
    company_name = models.CharField('Назва компанії',unique=True, max_length=50)
    contact_person_name = models.CharField('Ім\'я контактної персони', validators=[name_validator], max_length=50)
    contact_person_surname = models.CharField('Прізвище контактної персони',validators=[name_validator], max_length=50)
    phone_number = models.CharField('Телефон', validators=[phone_validator], unique=True, max_length=17)
    city = models.CharField('Місто', validators=[name_validator], max_length=50)
    email = models.EmailField('Пошта', unique=True, max_length=100)

    def save(self, *args, **kwargs):
        self.contact_person_name = self.contact_person_name.capitalize()
        self.contact_person_surname = self.contact_person_surname.capitalize()
        self.city = self.city.capitalize()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.company_name

    class Meta:
        app_label = 'catalog'


class Customer(models.Model):
    id_customer = models.AutoField(primary_key=True)
    customer_name = models.CharField('Ім\'я', validators=[name_validator], max_length=30)
    customer_surname = models.CharField('Прізвище', validators=[name_validator], max_length=30)
    customer_middle_name = models.CharField('По-батькові', validators=[name_validator], max_length=30)
    customer_city = models.CharField('Місто', validators=[name_validator], max_length=30)
    customer_address = models.CharField('Вулиця', validators=[name_validator], max_length=30)
    customer_number_of_house = models.IntegerField('Номер будинку', validators=[date_validator])
    customer_phone_number = models.CharField('Телефон', validators=[phone_validator], max_length=17)
    customer_email = models.EmailField('Пошта', unique=True, max_length=100)
    customer_passport_code = models.IntegerField('Код паспорту', unique=True, validators=[passport_validator])
    customer_date_of_birth = models.DateField('День народження')
    customer_password = models.CharField('Пароль', validators=[password_validator], max_length=40)
    customer_credit_card = models.CharField('Номер кредитної карти', validators=[card_validator], unique=True, max_length=19)

    def save(self, *args, **kwargs):
        self.customer_name = self.customer_name.capitalize()
        self.customer_surname = self.customer_surname.capitalize()
        self.customer_middle_name = self.customer_middle_name.capitalize()
        self.customer_city = self.customer_city.capitalize()
        self.customer_address = self.customer_address.capitalize()
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.customer_name}  {self.customer_surname}  {self.customer_middle_name}'

    class Meta:
        app_label = 'catalog'


class Item(models.Model):
    SIZE = (
        ('xxs', 'XXS'),
        ('xs', 'XS'),
        ('s', 'S'),
        ('m', 'M'),
        ('l', 'L'),
        ('xl', 'XL'),
        ('xxl', 'XXL')
    )
    TREATMENT = (
        ('Не оброблено', 'Не оброблено'),
        ('Потребує хімічної обробки', 'Потребує хімічної обробки'),
        ('Оброблено легкою хімією', 'Оброблено легкою хімією'),
        ('Оброблено важкою хімією', 'Оброблено важкою хімією'),
        ('Оброблено протиалергічними засобами', 'Оброблено протиалергічними засобами')
    )

    SEASONALITY = (
        ('Зима', 'Зима'),
        ('Весна', 'Весна'),
        ('Літо', 'Літо'),
        ('Осінь', 'Осінь'),
        ('Демісезон', 'Демісезон'),
        ('Любий', 'Любий'),
    )

    COLOR = (
        ('Бежевий', 'Бежевий'),
        ('Білий', 'Білий'),
        ('Блакитний', 'Блакитний'),
        ('Бордовий', 'Бордовий'),
        ('Жовтий', 'Жовтий'),
        ('Зелений', 'Зелений'),
        ('Коричневий', 'Коричневий'),
        ('Помаранчевий', 'Помаранчевий'),
        ('Рожевий', 'Рожевий'),
        ('Синій', 'Синій'),
        ('Сірий', 'Сірий'),
        ('Червоний', 'Червоний'),
        ('Чорний', 'Чорний'),
        ('Фіолетовий', 'Фіолетовий'),
        ('Інші кольори', 'Інші кольори'),
        ('Різнокольоровий', 'Різнокольоровий'),
        ('Принт', 'Принт'),
    )

    GENDER = (
        ('Жіночій', 'Жіночій'),
        ('Чоловічий', 'Чоловічий'),
        ('Унісекс', 'Унісекс')
    )

    STATE = (
        ('Є значні дефекти', 'Є значні дефекти'),
        ('Є незначні дефекти', 'Є незначні дефекти'),
        ('Трішки ношений', 'Трішки ношений'),
        ('Новий', 'Новий'),
    )
    id_item = models.AutoField(primary_key=True)
    supplier = models.ForeignKey(Supplier, on_delete=models.SET_NULL, null=True, verbose_name='Постачальник')
    fabric = models.ForeignKey(Fabric, on_delete=models.SET_NULL, null=True, verbose_name='Тканина')
    type = models.CharField('Тип',validators=[name_validator], max_length=30)
    brand = models.CharField('Бренд', max_length=30)
    size = models.CharField('Розмір', max_length=30,choices=SIZE)
    gender = models.CharField('Приналежність', max_length=30, choices=GENDER)
    color = models.CharField('Колір', max_length=30, choices=COLOR)
    chemical_treatment = models.CharField('Хімічна обробка', max_length=100, choices=TREATMENT)
    seasonality = models.CharField('Сезонність', max_length=100, choices=SEASONALITY)
    state = models.CharField('Стан', max_length=100, choices=STATE)
    price = models.FloatField('Ціна')

    def __str__(self):
        return f'{self.type}'

    class Meta:
        app_label = 'catalog'


class Receipt(models.Model):
    PAYMENT = (
        ('Готівка', 'Готівка'),
        ('Безготівковий розрахунок', 'Безготівковий розрахунок'),
    )
    DELIVERY = (
        ('Кур\'єрська доставка', 'Кур\'єрська доставка'),
        ('Термінова кур\'єрська доставка', 'Термінова кур\'єрська доставка'),
        ('Штатний кур\'єр', 'Штатний кур\'єр'),
        ('Самовивіз із офісу', 'Самовивіз із офісу'),
        ('Постамати', 'Постамати'),
        ('Пошта України', 'Пошта України'),
    )
    id_receipt = models.AutoField(primary_key=True)
    id_item = models.ForeignKey(Item, on_delete=models.SET_NULL, null=True, verbose_name='Товар', unique=True)
    id_customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, verbose_name='Покупець')
    number_of_receipt = models.IntegerField('Номер чеку', null=True, blank=True)
    date_of_purchase = models.DateTimeField('Дата покупки')

templates/catalog/tables/table_customer.html
{% extends 'catalog/pattern.html' %}
{% block title %}
Список клієнтів
{% endblock %}
{% block extra_css %}
{% endblock %}
{% block body %}
<div class="row">
            <div class="col" style="border: 3px solid #ad70c2;"><a class="p-2 text-dark" href="{% url 'lists_item' %}">Товари</a></div>
            <div class="col" style="border: 3px solid #ad70c2;"><a class="p-2 text-dark" href="{% url 'lists_supplier' %}">Постачальники</a></div>
            <div class="col" style="border: 3px solid #ad70c2;"><a class="p-2 text-dark" href="{% url 'lists_fabric' %}">Тканини</a></div>
            <div class="col" style="border: 3px solid #ad70c2;"><a class="p-2 text-dark" href="{% url 'lists_customer' %}">Клієнти</a></div>
            <div class="col" style="border: 3px solid #ad70c2;"><a class="p-2 text-dark" href="{% url 'lists_receipt' %}">Чеки</a></div></div>

<p></p>
<div style="margin-left: 6px;">
<form method="get" action="{% url 'lists_customer' %}">
    <input type="text" name="q" placeholder="Ваш запит" style="width: 300px; height: 20px; font-size: 14px; margin-right: 5px;">
    <button type="submit" style="font-size: 16px;">Пошук</button>
</form>
<div><form method="POST">
        {% csrf_token %} {{ sort_form.as_p }}
<input type="submit" value="Сортувати"/></form></div>
<p><a href="{% url 'new_customer' %}">Додати клієнта</a>
</div>

<div class="cont">
<div class="row">
        <div class="col" style="text-align: start; margin: 10px; padding: 10px;width: 250px; flex: none">
            <a class="p-2 text-dark">
                <form method="get" action="{% url 'lists_customer' %}">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Фільтрувати</button>
                </form>
            </a>
        </div>
        <div class="col" style="text-align: start; margin: 10px; padding: 10px;width: 10%;">
            <a class="p-2 text-dark">
                <div class="cont">
    <table>
        <thead>
        <tr>
            <th>ID</th>
            <th>Ім'я</th>
            <th>Прізвище</th>
            <th>По-батькові</th>
            <th>Місто</th>
            <th>Вулиця</th>
            <th>Номер будинку</th>
            <th>Телефон</th>
            <th>Пошта</th>
            <th>Код паспорту</th>
            <th>День народження</th>
            <th>Пароль</th>
            <th>Номер кредитної карти</th>
            <th>Дії</th>
        </tr>
    </thead>

    <tbody>
    {% if customers %}
        {% for customer in customers %}
        <tr>
            <td>{{ customer.id_customer }}</td>
            <td>{{ customer.customer_name }}</td>
            <td>{{ customer.customer_surname }}</td>
            <td>{{ customer.customer_middle_name }}</td>
            <td>{{ customer.customer_city }}</td>
            <td>{{ customer.customer_address }}</td>
            <td>{{ customer.customer_number_of_house }}</td>
            <td>{{ customer.customer_phone_number }}</td>
            <td>{{ customer.customer_email }}</td>
            <td>{{ customer.customer_passport_code }}</td>
            <td>{{ customer.customer_date_of_birth }}</td>
            <td>{{ customer.customer_password }}</td>
            <td>{{ customer.customer_credit_card }}</td>
            <td><a href="{% url 'edit_customer' customer.pk %}">Змінити</a>
            <a href="{% url 'delete_customer' customer.pk %}">Видалити</a>
            </td>
        </tr>
        {% endfor %}
    {% endif %}
    </tbody>
</table>
   </div>


            </a>
        </div>
    </div>
</div>
{% endblock %}

templates/catalog/tables/table_fabric.html
{% extends 'catalog/pattern.html' %}
{% block title %}
Список тканин
{% endblock %}
{% block extra_css %}

{% endblock %}
{% block body %}
<div class="row">
            <div class="col" style="border: 3px solid #ad70c2;"><a class="p-2 text-dark" href="{% url 'lists_item' %}">Товари</a></div>
            <div class="col" style="border: 3px solid #ad70c2;"><a class="p-2 text-dark" href="{% url 'lists_supplier' %}">Постачальники</a></div>
            <div class="col" style="border: 3px solid #ad70c2;"><a class="p-2 text-dark" href="{% url 'lists_fabric' %}">Тканини</a></div>
           <div class="col" style="border: 3px solid #ad70c2;"><a class="p-2 text-dark" href="{% url 'lists_customer' %}">Клієнти</a></div>
            <div class="col" style="border: 3px solid #ad70c2;"><a class="p-2 text-dark" href="{% url 'lists_receipt' %}">Чеки</a></div></div>

<p></p>
<form method="get" action="{% url 'lists_fabric' %}">
    <input type="text" name="q" placeholder="Ваш запит" style="width: 300px; height: 20px; font-size: 14px; margin-right: 5px;">
    <button type="submit" style="font-size: 16px;">Пошук</button>
</form>
<div><form method="POST">
        {% csrf_token %} {{ sort_form.as_p }}
<input type="submit" value="Сортувати"/></form></div>

<p><a href="{% url 'new_fabric' %}">Додати тканину</a>

<div class="cont">
    <div class="row">
        <div class="col" style="text-align: start; margin: 10px; padding: 10px; width: 250px; flex: none">
            <a class="p-2 text-dark">
                <form method="get" action="{% url 'lists_fabric' %}">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Фільтрувати</button>
                </form>
            </a>
        </div>
        <div class="col" style="text-align: start; margin: 10px; padding: 10px; width: 10%;">
            <a class="p-2 text-dark">
                <div class="cont">
            <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Назва тканини</th>
                <th>Щільність</th>
                <th>Еластичність</th>
                <th>Повітропроникність</th>
                <th>Текстура</th>
                <th>Стійкість до стиснення</th>
                <th>Стійкість кольору</th>
                <th>Дії</th>
            </tr>
        </thead>
        <tbody>
            {% if fabrics %}
            {% for fabric in fabrics  %}
            <tr>
                <td>{{ fabric.id_fabric }}</td>
                <td>{{ fabric.fabric_name }}</td>
                <td>{{ fabric.get_destiny_display }}</td>
                <td>{{ fabric.get_elasticity_display }}</td>
                <td>{{ fabric.get_breathability_display }}</td>
                <td>{{ fabric.get_surface_texture_display }}</td>
                <td>{{ fabric.get_compression_resistance_display }}</td>
                <td>{{ fabric.get_color_fastness_display }}</td>
                <td>
                    <a href="{% url 'edit_fabric' fabric.pk %}">Змінити</a><br>
                    <a href="{% url 'delete_fabric' fabric.pk %}">Видалити</a>
                </td>
            </tr>
            {% endfor %}
            {% endif %}
        </tbody>
    </table>

</div>
            </a>
        </div>
    </div>


</div>

{% endblock %}

templates/catalog/tables/table_item.html
{% extends 'catalog/pattern.html' %}
{% block title %}
Список товарів
{% endblock %}
{% block extra_css %}

{% endblock %}
{% block body %}
<div class="row">
            <div class="col" style="border: 3px solid #ad70c2;"><a class="p-2 text-dark" href="{% url 'lists_item' %}">Товари</a></div>
            <div class="col" style="border: 3px solid #ad70c2;"><a class="p-2 text-dark" href="{% url 'lists_supplier' %}">Постачальники</a></div>
            <div class="col" style="border: 3px solid #ad70c2;"><a class="p-2 text-dark" href="{% url 'lists_fabric' %}">Тканини</a></div>
            <div class="col" style="border: 3px solid #ad70c2;"><a class="p-2 text-dark" href="{% url 'lists_customer' %}">Клієнти</a></div>
            <div class="col" style="border: 3px solid #ad70c2;"><a class="p-2 text-dark" href="{% url 'lists_receipt' %}">Чеки</a></div></div>
<p></p>
<form method="get" action="{% url 'lists_item' %}">
    <input type="text" name="q" placeholder="Ваш запит" style="width: 300px; height: 20px; font-size: 14px; margin-right: 5px;">
    <button type="submit" style="font-size: 16px;">Пошук</button>
</form>
<div><form method="POST">
        {% csrf_token %} {{ sort_form.as_p }}
<input type="submit" value="Сортувати"/></form></div>
<p><a href="{% url 'new_lists' %}">Додати товар</a>

<div class="cont">
    <div class="row">
        <div class="col" style="text-align: start; margin: 10px; padding: 10px; width: 250px; flex: none">
            <a class="p-2 text-dark">
                <form method="get" action="{% url 'lists_item' %}">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Фільтрувати</button>
                </form>
            </a>
        </div>
        <div class="col" style="text-align: start; margin: 10px; padding: 10px; width: 10%;">
            <a class="p-2 text-dark">
                <div class="cont">
<table>
    <thead>
        <tr>
             <th>ID</th>
             <th>Тип</th>
             <th>Ціна</th>
             <th>Ціна зі знижкою</th>
             <th>Сезонність</th>
             <th>Бренд</th>
             <th>Розмір</th>
             <th>Приналежність</th>
             <th>Колір</th>
             <th>Тканина</th>
             <th>Хімічна обробка</th>
             <th>Стан</th>
             <th>Постачальник</th>
             <th>Дії</th>
        </tr>
    </thead>
    <tbody>
    {% if items %}
        {% for item in items %}
        <tr>
            <td>{{ item.id_item }}</td>
            <td>{{ item.type }}</td>
            <td>{{ item.price }} грн</td>
            <td>{{ item.discounted_price }} грн</td>
            <td>{{ item.get_seasonality_display }}</td>
            <td>{{ item.brand }}</td>
            <td>{{ item.get_size_display }}</td>
            <td>{{ item.get_gender_display }}</td>
            <td>{{ item.get_color_display }}</td>
            <td>{{ item.fabric }}</td>
            <td>{{ item.get_chemical_treatment_display }}</td>
            <td>{{ item.get_state_display }}</td>
            <td>{{ item.supplier }}</td>

            <td><a href="{% url 'edit_item' item.pk %}">Змінити</a>
            <a href="{% url 'delete_item' item.pk %}">Видалити</a>
            </td>
        </tr>
        {% endfor %}
    {% endif %}
         </tbody>
    </table>

</div>
            </a>
        </div>
    </div>


</div>
{% endblock %}

templates/catalog/tables/table_receipt.html
{% extends 'catalog/pattern.html' %}
{% block title %}
Список чеків
{% endblock %}
{% block extra_css %}

{% endblock %}
{% block body %}
<div class="row">
            <div class="col" style="border: 3px solid #ad70c2;"><a class="p-2 text-dark" href="{% url 'lists_item' %}">Товари</a></div>
            <div class="col" style="border: 3px solid #ad70c2;"><a class="p-2 text-dark" href="{% url 'lists_supplier' %}">Постачальники</a></div>
            <div class="col" style="border: 3px solid #ad70c2;"><a class="p-2 text-dark" href="{% url 'lists_fabric' %}">Тканини</a></div>
            <div class="col" style="border: 3px solid #ad70c2;"><a class="p-2 text-dark" href="{% url 'lists_customer' %}">Клієнти</a></div>
            <div class="col" style="border: 3px solid #ad70c2;"><a class="p-2 text-dark" href="{% url 'lists_receipt' %}">Чеки</a></div>
            </div>

<p></p>
<form method="get" action="{% url 'lists_receipt' %}">
    <input type="text" name="q" placeholder="Ваш запит" style="width: 300px; height: 20px; font-size: 14px; margin-right: 5px;">
    <button type="submit" style="font-size: 16px;">Пошук</button>
</form>
<div><form method="POST">
        {% csrf_token %} {{ sort_form.as_p }}
<input type="submit" value="Сортувати"/></form></div>

<p><a href="{% url 'new_receipt' %}">Додати чек</a>

<div class="cont">
<div class="row">
        <div class="col" style="text-align: start; margin: 10px; padding: 10px; width: 250px; flex: none">
            <a class="p-2 text-dark">
                <form method="get" action="{% url 'lists_receipt' %}">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit">Фільтрувати</button>
                </form>
            </a>
        </div>
        <div class="col" style="text-align: start; margin: 10px; padding: 10px; width: 10%;">
            <a class="p-2 text-dark">
                <div class="cont">
    <table>
        <thead>
        <tr>
            <th>ID</th>
            <th>Товар</th>
            <th>Покупець</th>
            <th>Номер чеку</th>
            <th>Дата покупки</th>
            <th>Вартість товару</th>
            <th>Тип доставки</th>
            <th>Тип оплати</th>
            <th>Дії</th>
        </tr>
    </thead>

    <tbody>
    {% if receipts %}
        {% for receipt in receipts %}
        <tr>
            <td>{{ receipt.id_receipt }}</td>
            <td>{{ receipt.id_item }}</td>
            <td>{{ receipt.id_customer }}</td>
            <td>№ {{ receipt.number_of_receipt|stringformat:"07d"  }}</td>
            <td>{{ receipt.date_of_purchase }}</td>
            <td>{{ receipt.the_item_cost }} грн</td>
            <td>{{ receipt.method_of_delivery }}</td>
            <td>{{ receipt.payment_type }}</td>
            <td><a href="{% url 'edit_receipt' receipt.pk %}">Змінити</a><br>
            <a href="{% url 'delete_receipt' receipt.pk %}">Видалити</a>
            </td>
        </tr>
        {% endfor %}
    {% endif %}
       </tbody>
    </table>

</div>
            </a>
        </div>
    </div>


</div>
{% endblock %}